services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # ✅ Используем порт 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
